import Image from "next/image";
import Header from "../header";

export default function Home() {
  return (
    <div className="">
      <main className="">
        <Header />
        <section className="pr-wrap">
          <h1 className="text-center my-5 text-4xl uppercase">Warm Audio Announces the Fluff Drive, The First-Ever Signature Pedal from Ryan “Fluff” Bruce of Riffs, Beards & Gear</h1>
          <p className="text-xl text-center italic">Warm Audio and Fluff take a classic high-gain staple and upgrade it with essential metal-ready mods, turning a fan-favorite circuit into a modern powerhouse.</p>
          <p><strong>Austin, TX – January 20, 2026 -</strong> <a href="https://warmaudio.com/">Warm Audio</a>, the leading manufacturer of faithful recreations of legendary recording gear and guitar pedals, is proud to announce the release of the Limited Edition Fluff Drive, their first signature pedal created with Ryan “Fluff” Bruce of <a href="https://www.youtube.com/@RiffsAndBeards">Riffs, Beards & Gear</a>—one of the most trusted and wildly popular voices in heavy guitar tone and pedal reviews. A signature screaming overdrive dialed in specifically for metal and high-gain guitar, the Fluff Drive takes a legendary ’80s platform and elevates it with amp-driving power, a modded mid-enhance circuit and low-boost control, and a high/low noise gate. After pushing thousands of pedals to their limits, Fluff added critical mods and helped refine this legendary circuit into a stompbox that delivers the aggressive mids, tight punch, and instant clarity that modern rigs demand. The Limited Edition Fluff Drive (MSRP $199 | 219 € inc. VAT | 209 £ inc. VAT)) is available exclusively at Sweetwater in the US and at authorized retailers worldwide.</p>
          <p>“I’ve tested a ridiculous number of pedals over the years, so when it came time to do a signature drive, I knew I needed a partner who actually cares about components and understands what makes the legendary circuits legendary. Warm Audio was that perfect partner,” said Ryan “Fluff” Bruce. “They’re obsessed with the details and are circuit-obsessed enough to dig deep into every diode and resistor, but also experienced enough to help me nail the classic sound players expect.”</p>
          <p>Fluff continues, “Together with them, I wanted to fix every issue I’ve ever had dialing in metal tones on similar pedals or even the original. Warm worked with me on even the tiniest modification until the pedal did exactly what I always wished those circuits would do. The Fluff Drive is the result: the classic vibe, but with the ideal controls for metal implemented the way I’ve always wanted.”</p>
          <p>The Fluff Drive is a signature pedal built from real-world experience, delivering the fast, focused midrange and tight low-end response metal and hardcore players rely on to push amps into controlled chaos. Its upgraded design includes a modded low-boost circuit for down-tuned guitars, baritones, and 7–8 string clarity; a pre/post mid-enhance switch for shaping attack and presence; a high/low/off noise gate for everything from crushing palm-mutes to wide-open leads; and an 18V voltage-boost mode for added headroom and cleaner gain. Premium analog components, including JRC4558 op-amps, discrete transistors, JFETs, and an internal voltage-doubler supply, ensure the pedal slots effortlessly at the front of any high-gain rig, hitting an amp hard and driving power tubes into rich saturation far beyond standard preamp gain. The result is the punch, response, and tonal control Fluff demands in his own setups.</p>
          <p>Like all Warm Audio gear, every single Fluff Drive is meticulously hand-tested and inspected by trained technicians with a passion for making music in Austin, TX, and comes with a 5-year warranty. The Limited Edition <strong>Fluff Drive </strong> is available in two colors: Teal (WA-FLFT) and White (WA-FLFW). Both MSRP $199 | 219 € inc. VAT | 209 £ inc. VAT) are available at launch exclusively at Sweetwater in the US and specific authorized retailers worldwide. For more information, visit <a href="www.warmaudio.com/fluff-drive">www.warmaudio.com/fluff-drive</a>.</p>
          
          
          
          <h2 className="my-5 text-2xl uppercase">About Ryan “Fluff” Bruce</h2>
          <p>Ryan “Fluff” Bruce is a guitarist, producer, and the creator of Riffs, Beards & Gear, one of the most influential and widely followed guitar channels in the heavy music world. With a career built on transparency, humor, and a no-nonsense approach to tone, Fluff has earned the trust of millions of players who rely on his honest gear reviews, in-depth demos, and real-world rig advice. Beyond YouTube, Fluff is an active musician, touring guitarist, and recording artist whose hands-on experience with thousands of pedals, amps, and studio tools gives him a unique perspective on what heavy guitarists truly need. His commitment to demystifying tone and empowering players at every skill level has made him a respected voice across the metal, hardcore, and broader guitar community.</p>
          <h2 className="my-5 text-2xl uppercase">About Warm Audio</h2>
          <p>Warm Audio began in 2011 in founder Bryce Young’s garage upon the simple principle of building high-end recording products that were sonically equal to renowned products of the past, but to also make them affordable. Warm Audio is now an Inc. 5000 company and industry-leading manufacturer of classic-inspired preamps, compressors, limiters, equalizers, microphones, guitar pedals, and more. Headquartered in Austin, TX, Warm Audio houses state-of-the-art recording facilities with two world-class recording studios where the team applies the “Warm Formula” of design to every product by ensuring that they deliver the very best in legendary sound at unprecedented value. For more information, visit <a href="www.warmaudio.com">www.warmaudio.com</a>.</p>
       </section>
      </main>
    </div>
  );
}
